# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kdiscover < Formula
  desc "Utility for listing and exporting config for K8s Clusters"
  homepage ""
  version "0.1.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mateimicu/kdiscover/releases/download/v0.1.3/kdiscover_0.1.3_darwin_arm64.tar.gz"
      sha256 "9b165434511e64840b5b8f2dc92a68a6a83255c168fbcf6ed7f084742cbe010a"

      def install
        bin.install "kdiscover"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mateimicu/kdiscover/releases/download/v0.1.3/kdiscover_0.1.3_darwin_amd64.tar.gz"
      sha256 "0cdfd2ae43c13e113b898568baeb443d180c8c95f68f26eb9b3526a25ebf54e6"

      def install
        bin.install "kdiscover"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mateimicu/kdiscover/releases/download/v0.1.3/kdiscover_0.1.3_linux_arm64.tar.gz"
      sha256 "2ea7565a72d84da9937b99a35c91fc47436ccfcda7b0970439e03befa10770af"

      def install
        bin.install "kdiscover"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mateimicu/kdiscover/releases/download/v0.1.3/kdiscover_0.1.3_linux_amd64.tar.gz"
      sha256 "60ae25cd4ec869da87252d4bdafc92f1ac570ed54b62847feb8530893fef30ab"

      def install
        bin.install "kdiscover"
      end
    end
  end

  test do
    system "#{bin}/kdiscover --version"
  end
end
