# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kdiscover < Formula
  desc "Utility for listing and exporting config for K8s Clusters"
  homepage ""
  version "0.1.6"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mateimicu/kdiscover/releases/download/v0.1.6/kdiscover_v0.1.6_darwin_arm64.tar.gz"
      sha256 "fa381d824244708a9a030b98793768280965a2755b44fbecdb0b0206d670636f"

      def install
        bin.install "kdiscover"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mateimicu/kdiscover/releases/download/v0.1.6/kdiscover_v0.1.6_darwin_amd64.tar.gz"
      sha256 "f71d940c517cef9d826f83b7202dcc112cda0923514b6c72d6e5d2e9514775e2"

      def install
        bin.install "kdiscover"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mateimicu/kdiscover/releases/download/v0.1.6/kdiscover_v0.1.6_linux_amd64.tar.gz"
      sha256 "2e12eef8b35a521c58785aceb3b24891c2ef42140e41e5d8c7707aef2f18108e"

      def install
        bin.install "kdiscover"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mateimicu/kdiscover/releases/download/v0.1.6/kdiscover_v0.1.6_linux_arm64.tar.gz"
      sha256 "f1db5e89ede0beb44054c6583039867a80c638a9f1ca5d10afb38c59dd4284b8"

      def install
        bin.install "kdiscover"
      end
    end
  end

  test do
    system "#{bin}/kdiscover --version"
  end
end
